const PORT = 4000;
const REFRESH_SPEED = 3000;
const NDZ_MID_POINT = {
	x: 250000,
	y: 250000,
};
const NDZ_RADIUS = 100000;
const EXPIRATION_TIME = 600000;
const DATABASE_FILE_NAME = "db.json";
const API_URL_HEALTH = "/health";

export {
	PORT,
	REFRESH_SPEED,
	NDZ_MID_POINT,
	NDZ_RADIUS,
	EXPIRATION_TIME,
	DATABASE_FILE_NAME,
	API_URL_HEALTH,
};
